version: '3'
services:


  
  mongodb:
    image: mongo
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
#    restart: on-failure
    depends_on:
    - mongodb    





