version: '3'
services:


  
  mongodb:
    image: mongo
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
#    restart: on-failure
    depends_on:
    - mongodb    


  
  postgresdb:          # name : also the hostname
    image: postgres    # image downloaded from DockerHub
    ports:
    - 5555:5432        # maps port 5432 *inside* the container to port 5555 on my local machine
    environment:       # set an environment variable
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=pass123
    - POSTGRES_DB=dbname

  etl:
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on:
    - mongodb
    - postgresdb




  slack_bot:
    build: slack/
    volumes:
      - ./slack/:/app
    restart: on-failure
    depends_on:
      - etl
      - mongodb
      - postgresdb

